version: '3.7'
services:
  mysql:
    container_name: onwetwoclass-mysql
    environment:
      ROOT_PASSWORD : 1234
    ports:
      - "3306:3306"

  es:
    build:
      context: "nori/Dockerfile"
      args:
        ELK_VERSION: 7.15.2
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=OneTwoClass
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    # Elasticsearch Start Dependency
    depends_on:
      - es
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge