server:
  port: 8080

spring:
  redis:
    port: 6379
    host: localhost

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/onetwoday?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: false

jwt:
  secret: onetwoclass
  validate: 1000 * 60 * 60 * 24