server:
  port: 8080

spring:
  redis:
    port: 6379
    host: redis-container

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://mysql-container:3306/onetwoclass?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

jwt:
  secret: onetwoclass
  validate: 1000 * 60 * 60